name: log_in
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.1.0 <4.0.0'
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  flutter_screenutil: ^5.9.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
flutter:
  uses-material-design: true
  assets:
    - assets/icons/
    - assets/image/
  #   - images/a_dot_ham.jpeg
  fonts:
    - family: Jost
      fonts:
        - weight: 900
        - asset: assets/fonts/jost/Jost-Black.ttf
        - asset: assets/fonts/jost/Jost-BlackItalic.ttf
          weight: 700
        - asset: assets/fonts/jost/Jost-Bold.ttf
        - asset: assets/fonts/jost/Jost-BoldItalic.ttf
          weight: 800
        - asset: assets/fonts/jost/Jost-ExtraBold.ttf
        - asset: assets/fonts/jost/Jost-ExtraBoldItalic.ttf
          weight: 200
        - asset: assets/fonts/jost/Jost-ExtraLight.ttf
        - asset: assets/fonts/jost/Jost-ExtraLightItalic.ttf
        - asset: assets/fonts/jost/Jost-Italic.ttf
          weight: 300
        - asset: assets/fonts/jost/Jost-Light.ttf
        - asset: assets/fonts/jost/Jost-LightItalic.ttf
          weight: 500
        - asset: assets/fonts/jost/Jost-Medium.ttf
        - asset: assets/fonts/jost/Jost-MediumItalic.ttf
        - asset: assets/fonts/jost/Jost-Regular.ttf
          weight: 600
        - asset: assets/fonts/jost/Jost-SemiBold.ttf
        - asset: assets/fonts/jost/Jost-SemiBoldItalic.ttf
          weight: 100
        - asset: assets/fonts/jost/Jost-Thin.ttf
        - asset: assets/fonts/jost/Jost-ThinItalic.ttf
    - family: Monserrat
      fonts:
        - weight: 900
        - asset: assets/fonts/monserrat/Montserrat-Black.ttf
        - asset: assets/fonts/monserrat/Montserrat-BlackItalic.ttf
          weight: 700
        - asset: assets/fonts/monserrat/Montserrat-Bold.ttf
        - asset: assets/fonts/monserrat/Montserrat-BoldItalic.ttf
          weight: 800
        - asset: assets/fonts/monserrat/Montserrat-ExtraBold.ttf
        - asset: assets/fonts/monserrat/Montserrat-ExtraBoldItalic.ttf
          weight: 200
        - asset: assets/fonts/monserrat/Montserrat-ExtraLight.ttf
        - asset: assets/fonts/monserrat/Montserrat-ExtraLightItalic.ttf
        - asset: assets/fonts/monserrat/Montserrat-Italic.ttf
          weight: 300
        - asset: assets/fonts/monserrat/Montserrat-Light.ttf
        - asset: assets/fonts/monserrat/Montserrat-LightItalic.ttf
          weight: 500
        - asset: assets/fonts/monserrat/Montserrat-Medium.ttf
        - asset: assets/fonts/monserrat/Montserrat-MediumItalic.ttf
        - asset: assets/fonts/monserrat/Montserrat-Regular.ttf
          weight: 600
        - asset: assets/fonts/monserrat/Montserrat-SemiBold.ttf
        - asset: assets/fonts/monserrat/Montserrat-SemiBoldItalic.ttf
          weight: 100
        - asset: assets/fonts/monserrat/Montserrat-Thin.ttf
        - asset: assets/fonts/monserrat/Montserrat-ThinItalic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
